//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberPlatGate.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberPlatGate.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pubkeys {
            get {
                object obj = ResourceManager.GetObject("pubkeys", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] secret {
            get {
                object obj = ResourceManager.GetObject("secret", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000051701SM000002560000025600000125
        ///api17032            00017033
        ///                    00000000
        ///BEGIN
        ///SD=17031
        ///AP=17032
        ///OP=17034
        ///DATE=07.01.2018 21:23:19
        ///SESSION=71838f9a01294d109a301b3971dcc0c0
        ///NUMBER=9261112233
        ///ACCOUNT=
        ///AMOUNT=1234.56
        ///AMOUNT_ALL=1249.99
        ///REQ_TYPE=1
        ///PAY_TOOL=0
        ///TERM_ID=
        ///COMMENT=test test 0123456789
        ///ACCEPT_KEYS=64182
        ///NO_ROUTE=1
        ///END
        ///BEGIN SIGNATURE
        ///iQBRAwkBAABCiVpSZZ8BATq5AgCw9zbMNvYm6a6wJWopMZ59nifJimxAqoOirslX
        ///tXVpcfNf3T4Og+7Xo+Jzgve+vZAj4eng0zXFm+GSRIYL6frUsAHH
        ///=HjNF
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServerCheckResponse {
            get {
                return ResourceManager.GetString("ServerCheckResponse", resourceCulture);
            }
        }
    }
}
