//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberPlatGate.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberPlatGate.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pubkeys {
            get {
                object obj = ResourceManager.GetObject("pubkeys", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] secret {
            get {
                object obj = ResourceManager.GetObject("secret", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000043801SM000001770000017700000125
        ///0J0005              00064182
        ///                    00000000
        ///BEGIN
        ///DATE=08.01.2018 12:54:21
        ///SESSION=mRdRr5lqY3TaZwbSweOX
        ///ERROR=0
        ///RESULT=0
        ///OPNAME=
        ///ACCOUNT=
        ///ERRMSG=
        ///AUTHCODE=
        ///TRANSID=
        ///REST=99999308910842.25
        ///GATEWAY_IN=9
        ///GATEWAY_OUT=9
        ///
        ///END
        ///BEGIN SIGNATURE
        ///iQBRAwkBAAD6tlpTP80BAbvnAfsEdCFUJo/uhPTtWqnvSi9IeiFo/u1Nk4xEkqXQ
        ///tn4ZZczWP/x43x9tSk/unQc1ywg70bP8rJIkDq7QUyT1iaW8sAHH
        ///=qRgr
        ///END SIGNATURE.
        /// </summary>
        internal static string ServerCheckResponse {
            get {
                return ResourceManager.GetString("ServerCheckResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000038801SM000001270000012700000125
        ///0J0005              00064182
        ///                    00000000
        ///BEGIN
        ///DATE=08.01.2018 16:04:25
        ///SESSION=rYuD8SkcMq3fX92fSild
        ///ERROR=0
        ///RESULT=0
        ///TRANSID=1000010856873
        ///GATEWAY_IN=9
        ///GATEWAY_OUT=9
        ///
        ///END
        ///BEGIN SIGNATURE
        ///iQBRAwkBAAD6tlpTbFkBAYLrAgDCXaFN5iwZ30ER9v3QZ3iwQiTMsjWrlVm4Yuf1
        ///a67TXiHQ0CmCvw/baaC4MIrSCk+ri4+Ic49qh2+TsjP6FbiAsAHH
        ///=4LiN
        ///END SIGNATURE.
        /// </summary>
        internal static string ServerPayResponse {
            get {
                return ResourceManager.GetString("ServerPayResponse", resourceCulture);
            }
        }
    }
}
